name: 'Repo Sync Action'

description: 'Sync repositories using repo tool with manifest'

inputs:
  manifest:
    description: 'manifest file to use'
    required: true
    default: 'lubancat_linux_generic.xml'
  token:
    description: 'GitHub token for authentication'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Install prerequisites
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        git ssh make gcc libssl-dev liblz4-tool u-boot-tools curl \
        expect g++ patchelf chrpath gawk texinfo chrpath diffstat binfmt-support \
        qemu-user-static live-build bison flex fakeroot cmake gcc-multilib g++-multilib \
        unzip device-tree-compiler python3-pip libncurses5-dev python3-pyelftools \
        dpkg-dev

        # Install repo tool
        curl https://storage.googleapis.com/git-repo-downloads/repo > /tmp/repo
        chmod a+x /tmp/repo
        sudo mv /tmp/repo /usr/local/bin/repo

    - name: Setup Build Environment and Build Component
      id: build
      shell: bash
      run: |
        # Configure git to use GitHub token for private repos
        git config --global url."https://${{ inputs.token }}@github.com/".insteadOf "https://github.com/"

        # Configure git user and email for BitBake operations
        git config --global user.name "diverger"
        git config --global user.email "diverger@live.cn"

        # Option: Use your forked manifest instead of official STM manifest
        repo --trace init --depth=1 -u https://github.com/diverger/manifest-rockchip.git -b handy -m ${{ inputs.manifest }}
        repo sync -c -j$(nproc)
