name: Sync the repo

on:
  workflow_dispatch:
    inputs:
      manifest:
        description: 'manifest to sync'
        required: false
        default: ''
        type: string
      runner:
        description: 'Runner label to use for the job (e.g. self-hosted or ubuntu-latest)'
        required: false
        default: 'self-hosted'
        type: string

env:
  RECIPE_REP: 'diverger/manifest-rockchip'
  RECIPE_REF: 'handy'
  RECIPE_DIR: "."

jobs:
  sync:
    runs-on: ${{ inputs.runner }}
    name: Sync
    timeout-minutes: 360  # 6 hours max

    steps:
      - name: Get more disk space
        # Skip aggressive disk cleanup on self-hosted runners to avoid
        # deleting other jobs' data or system files. This step will only
        # run when the runner is NOT labeled `self-hosted`.
        if: ${{ !contains(github.runner.labels, 'self-hosted') }}
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Checkout build repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.RECIPE_REP }}
          ref: ${{ env.RECIPE_REF }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          path: ${{ env.RECIPE_DIR }}
          clean: false
          fetch-depth: 1
          lfs: true

      - name: Repo Sync
        uses: ./.github/actions/repo-sync
        with:
          manifest: ${{ inputs.manifest }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}
